config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => { registrations: 'registrations' }
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :users
	root to: "home#index"

  
	get "/targets/index", to: "targets#index", as: "targets_index"
	get "/targets/:id", to: "targets#show", as: "targets_show"
	
	get "/exercises/new", to: "exercises#new", as: "new_exercise"
	post "exercises/new", to: "exercises#create", as: "create_exercise"
	get "/exercises/:body_part", to: "exercises#index", as: "display_exercises"
	
	post "/users/edit", to: "user#update"
	get '/users/water', to: "user#hydrate"
	get "/targets/show", to: "targets#show", as: "specific_target_exercises"

end

app/models/exercise.rb
class Exercise < ApplicationRecord
  has_and_belongs_to_many :targets
end

app/models/target.rb
class Target < ApplicationRecord
  has_and_belongs_to_many :exercises
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
  		devise_parameter_sanitizer.permit(:sign_in) do |user_params|
    		user_params.permit(:name, :email, :water)
  		end
	end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def new
    @exercise = Exercise.new
  end

  def create
    @exercise = Exercise.new(exercise_params)

    if @exercise.save && (["Butt", "Arms", "Shoulders", "Legs", "Chest", "Back"].include? @exercise.body_part)
      redirect_to display_exercises_path(body_part: @exercise.body_part)
    else
      redirect_to new_exercise_path, :flash => { :error => "Fill out all details for the exercise you're adding!"}
    end
  end


  # def show
  #   @exercise = Exercise.all
  # end


  def index
    @exercise = Exercise.where(body_part: params[:body_part])

  end

  private
    def exercise_params
      params.require(:exercise).permit(:title, :description, :duration, :body_part)
    end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
	def index
		@targets = Target.all
		
	end

	def show
		@target = Target.find(params[:id])
		# @target = @exercise.body_part
		@exercise = Exercise.where(target_id: params[:id])
		# render :show
	end
end

app/views/exercises/index.html.erb
<% @exercise.each do |exercise| %>
    <div> 
    Title: <%= exercise.title %> <br>
  	Description: <%= exercise.description %> <br>
  	Duration: <%= exercise.duration %> <br>
  <br></div>
<% end %>

<a href="new">Create New Exercise</a>

app/views/exercises/new.html.erb
<h1> Create New Exercise! </h1>

<%= form_for :exercise do |f| %>
  Title: <%= f.text_field :title %><br />
  Description: <%= f.text_field :description %><br />
  Duration: <%= f.number_field :duration %><br />
  Body Part: <%= f.text_field :body_part %><br />

   <%= f.submit %>
<% end %>

app/views/home/index.html.erb
<html>
	<head>
		<title>My Gym Buddy</title>
	</head>
	<body>
        <div class="header">
		<h3 class="first">Welcome to</h3>
        <h3 class="second">My Gym Buddy</h3>
        </div>
        <div class="body">

        <p> My Gym Buddy is an application that creates workouts for users according to their desired target area. To get started, <%= link_to 'click here', targets_index_path %> to choose exercises for specific body parts.</p> 


        <p> <%= link_to 'Create New Exercises', new_exercise_path %> </p>
        </div>
		
	</body>
</html>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="topnav" data-topbar>
    <div class="left-nav">
        <p>Users: <%= User.count %> registered</p>
    </div>
    
    <%= render 'layouts/navigation_links' %>
    <li class="name link"><%= link_to 'Home', root_path %></li>

</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li class="link"><%= link_to 'Profile', edit_user_registration_path %></li>
  <li class="link"><%= link_to 'Log Out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li class="link"><%= link_to 'Login', new_user_session_path %></li>
  <li class="link"><%= link_to 'Join My Gym Buddy', new_user_registration_path %></li>
<% end %>

app/views/targets/index.html.erb
<h1 class="bodyparts"> Choose your workout </h1>
<% @targets.each do |target| %>
	<h3 class="bodypart"> <%= link_to target.body, targets_show_path(target) %> </h3>

	

<% end %>

app/views/targets/show.html.erb
<% @target.exercises.each do |e| %>
	
		<p>Title: <%= e.title %></p>
		<p>Description: <%= e.description %></p>
		<p>Duration: <%= e.duration %> </p>
	
<% end %>